# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-31 04:27
from __future__ import unicode_literals

import cat_mp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1024)),
                ('fpath', models.FileField(upload_to=cat_mp.models.upload_to)),
                ('album_id', models.CharField(db_index=True, max_length=128)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128)),
                ('album_id', models.CharField(default='-1', max_length=128)),
                ('ropenid', models.CharField(max_length=128)),
                ('rtime', models.CharField(max_length=32)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('openid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('avatarUrl', models.CharField(max_length=200)),
                ('nickName', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='reward',
            index_together=set([('openid', 'album_id')]),
        ),
        migrations.AlterIndexTogether(
            name='image',
            index_together=set([('openid', 'album_id', 'index')]),
        ),
    ]
