# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-22 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_mp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ftime',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
